apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secure-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bansi-pambhar/secure-supplychain-gitops
    targetRevision: main
    path: apps/secure-app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: secure-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
